/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MárioLiberato
 */
import java.io.File;
import java.util.*;
public class JobApplicationUI extends javax.swing.JFrame {

    /**
     * Creates new form JobApplicationUI
     */
    public JobApplicationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        educationLevelGroup = new javax.swing.ButtonGroup();
        skillButtonGroup = new javax.swing.ButtonGroup();
        fullNameTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        phoneNumberTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        dayTextBox = new javax.swing.JTextField();
        monthTextBox = new javax.swing.JTextField();
        yearTextBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fullNameTextBox.setToolTipText("");
        fullNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTextBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Company X Job Application Form");

        jLabel2.setText("Full Name:");

        jLabel3.setText("Education Level:");

        educationLevelGroup.add(jRadioButton1);
        jRadioButton1.setText("None");

        educationLevelGroup.add(jRadioButton2);
        jRadioButton2.setText("Primary School");
        jRadioButton2.setToolTipText("");

        educationLevelGroup.add(jRadioButton3);
        jRadioButton3.setText("High School");

        educationLevelGroup.add(jRadioButton4);
        jRadioButton4.setText("Bachelor's Degree");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        educationLevelGroup.add(jRadioButton5);
        jRadioButton5.setText("Master's Degree");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        educationLevelGroup.add(jRadioButton6);
        jRadioButton6.setText("Doctorate");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Skills:");

        jLabel5.setText("Phone Number");

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Birthdate (dd-mm-yyyy)");
        
        setCheckboxes();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox9)
                                    .addComponent(jCheckBox10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox11)
                                    .addComponent(jCheckBox12)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jCheckBox15)
                                    .addComponent(jCheckBox16)
                                    .addComponent(jCheckBox17)
                                    .addComponent(jCheckBox18)
                                    .addComponent(jCheckBox19)
                                    .addComponent(jCheckBox20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox21)
                                    .addComponent(jCheckBox22)
                                    .addComponent(jCheckBox23)
                                    .addComponent(jCheckBox24)
                                    .addComponent(jCheckBox25)
                                    .addComponent(jCheckBox26)
                                    .addComponent(jCheckBox27)
                                    .addComponent(jCheckBox28)
                                    .addComponent(jCheckBox29)
                                    .addComponent(jCheckBox30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox31)
                                    .addComponent(jCheckBox32)
                                    .addComponent(jCheckBox33)
                                    .addComponent(jCheckBox34)
                                    .addComponent(jCheckBox35)
                                    .addComponent(jCheckBox36)
                                    .addComponent(jCheckBox37)
                                    .addComponent(jCheckBox38)
                                    .addComponent(jCheckBox39)
                                    .addComponent(jCheckBox40))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox41)
                                    .addComponent(jCheckBox42)
                                    .addComponent(jCheckBox43)
                                    .addComponent(jCheckBox44)
                                    .addComponent(jCheckBox45)
                                    .addComponent(jCheckBox46)
                                    .addComponent(jCheckBox47)
                                    .addComponent(jCheckBox48)
                                    .addComponent(jCheckBox49)
                                    .addComponent(jCheckBox50)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monthTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(phoneNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox10))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox20)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox30)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox36)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox37)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox39)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox40)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox50)))
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextBoxActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
		jCheckBox1.setSelected(false);
		jCheckBox2.setSelected(false);
		jCheckBox3.setSelected(false);
		jCheckBox4.setSelected(false);
		jCheckBox5.setSelected(false);
		jCheckBox6.setSelected(false);
		jCheckBox7.setSelected(false);
		jCheckBox8.setSelected(false);
		jCheckBox9.setSelected(false);
		jCheckBox10.setSelected(false);
		jCheckBox11.setSelected(false);
		jCheckBox12.setSelected(false);
		jCheckBox13.setSelected(false);
		jCheckBox14.setSelected(false);
		jCheckBox15.setSelected(false);
		jCheckBox16.setSelected(false);
		jCheckBox17.setSelected(false);
		jCheckBox18.setSelected(false);
		jCheckBox19.setSelected(false);
		jCheckBox20.setSelected(false);
		jCheckBox21.setSelected(false);
		jCheckBox22.setSelected(false);
		jCheckBox23.setSelected(false);
		jCheckBox24.setSelected(false);
		jCheckBox25.setSelected(false);
		jCheckBox26.setSelected(false);
		jCheckBox27.setSelected(false);
		jCheckBox28.setSelected(false);
		jCheckBox29.setSelected(false);
		jCheckBox30.setSelected(false);
		jCheckBox31.setSelected(false);
		jCheckBox32.setSelected(false);
		jCheckBox33.setSelected(false);
		jCheckBox34.setSelected(false);
		jCheckBox35.setSelected(false);
		jCheckBox36.setSelected(false);
		jCheckBox37.setSelected(false);
		jCheckBox38.setSelected(false);
		jCheckBox39.setSelected(false);
		jCheckBox40.setSelected(false);
		jCheckBox41.setSelected(false);
		jCheckBox42.setSelected(false);
		jCheckBox43.setSelected(false);
		jCheckBox44.setSelected(false);
		jCheckBox45.setSelected(false);
		jCheckBox46.setSelected(false);
		jCheckBox47.setSelected(false);
		jCheckBox48.setSelected(false);
		jCheckBox49.setSelected(false);
		jCheckBox50.setSelected(false);
		jRadioButton1.setSelected(true);
		fullNameTextBox.setText("");
		phoneNumberTextBox.setText("");
		dayTextBox.setText("");
		monthTextBox.setText("");
		yearTextBox.setText("");
		jRadioButton1.setSelected(true);

    }//GEN-LAST:event_resetButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
		
		// Count skills selected
		int count = 0;
		List<Integer> skillList = new ArrayList<Integer>();
		if (jCheckBox1.isSelected()) { count++; skillList.add(1); }
		if (jCheckBox2.isSelected()) { count++; skillList.add(2); }
		if (jCheckBox3.isSelected()) { count++; skillList.add(3); }
		if (jCheckBox4.isSelected()) { count++; skillList.add(4); }
		if (jCheckBox5.isSelected()) { count++; skillList.add(5); }
		if (jCheckBox6.isSelected()) { count++; skillList.add(6); }
		if (jCheckBox7.isSelected()) { count++; skillList.add(7); }
		if (jCheckBox8.isSelected()) { count++; skillList.add(8); }
		if (jCheckBox9.isSelected()) { count++; skillList.add(9); }
		if (jCheckBox10.isSelected()) { count++; skillList.add(10); }
		if (jCheckBox11.isSelected()) { count++; skillList.add(11); }
		if (jCheckBox12.isSelected()) { count++; skillList.add(12); }
		if (jCheckBox13.isSelected()) { count++; skillList.add(13); }
		if (jCheckBox14.isSelected()) { count++; skillList.add(14); }
		if (jCheckBox15.isSelected()) { count++; skillList.add(15); }
		if (jCheckBox16.isSelected()) { count++; skillList.add(16); }
		if (jCheckBox17.isSelected()) { count++; skillList.add(17); }
		if (jCheckBox18.isSelected()) { count++; skillList.add(18); }
		if (jCheckBox19.isSelected()) { count++; skillList.add(19); }
		if (jCheckBox20.isSelected()) { count++; skillList.add(20); }
		if (jCheckBox21.isSelected()) { count++; skillList.add(21); }
		if (jCheckBox22.isSelected()) { count++; skillList.add(22); }
		if (jCheckBox23.isSelected()) { count++; skillList.add(23); }
		if (jCheckBox24.isSelected()) { count++; skillList.add(24); }
		if (jCheckBox25.isSelected()) { count++; skillList.add(25); }
		if (jCheckBox26.isSelected()) { count++; skillList.add(26); }
		if (jCheckBox27.isSelected()) { count++; skillList.add(27); }
		if (jCheckBox28.isSelected()) { count++; skillList.add(28); }
		if (jCheckBox29.isSelected()) { count++; skillList.add(29); }
		if (jCheckBox30.isSelected()) { count++; skillList.add(30); }
		if (jCheckBox31.isSelected()) { count++; skillList.add(31); }
		if (jCheckBox32.isSelected()) { count++; skillList.add(32); }
		if (jCheckBox33.isSelected()) { count++; skillList.add(33); }
		if (jCheckBox34.isSelected()) { count++; skillList.add(34); }
		if (jCheckBox35.isSelected()) { count++; skillList.add(35); }
		if (jCheckBox36.isSelected()) { count++; skillList.add(36); }
		if (jCheckBox37.isSelected()) { count++; skillList.add(37); }
		if (jCheckBox38.isSelected()) { count++; skillList.add(38); }
		if (jCheckBox39.isSelected()) { count++; skillList.add(39); }
		if (jCheckBox40.isSelected()) { count++; skillList.add(40); }
		if (jCheckBox41.isSelected()) { count++; skillList.add(41); }
		if (jCheckBox42.isSelected()) { count++; skillList.add(42); }
		if (jCheckBox43.isSelected()) { count++; skillList.add(43); }
		if (jCheckBox44.isSelected()) { count++; skillList.add(44); }
		if (jCheckBox45.isSelected()) { count++; skillList.add(45); }
		if (jCheckBox46.isSelected()) { count++; skillList.add(46); }
		if (jCheckBox47.isSelected()) { count++; skillList.add(47); }
		if (jCheckBox48.isSelected()) { count++; skillList.add(48); }
		if (jCheckBox49.isSelected()) { count++; skillList.add(49); }
		if (jCheckBox50.isSelected()) { count++; skillList.add(50); }
		
        // Add the User to the file.
        User tempUser = new User(count);
        
        List<User> userTable = new ArrayList<User>();
        String tableFileName = "table.tb";
        try
        {
			userTable = Main.readUserTable(Main.readFile(new File(tableFileName)));
		} catch (Exception e)
		{
			// No user table? Make the table empty
		}
        
        // Add data to user
        
        int getLastID = 0;
        if (userTable.size() > 0)
			getLastID = userTable.get(userTable.size()-1).userID;
        
        tempUser.userID = getLastID + 1;
        tempUser.addSkill(skillList);
        int educationLevelID = 0;
        if (jRadioButton1.isSelected()) educationLevelID = 0;
        if (jRadioButton2.isSelected()) educationLevelID = 1;
        if (jRadioButton3.isSelected()) educationLevelID = 2;
        if (jRadioButton4.isSelected()) educationLevelID = 3;
        if (jRadioButton5.isSelected()) educationLevelID = 4;
        if (jRadioButton6.isSelected()) educationLevelID = 5;      
        tempUser.educationLevelID = educationLevelID;
        
        if (fullNameTextBox.getText().replace(";", "").replace(",", "").trim().length() > 0 && isInteger(phoneNumberTextBox.getText()))
        {
			tempUser.userName = fullNameTextBox.getText();
			try
			{
				tempUser.phoneNumber = phoneNumberTextBox.getText();
				if (!isInteger(dayTextBox.getText()) || Integer.valueOf(dayTextBox.getText()) < 1 || Integer.valueOf(dayTextBox.getText()) > 31) throw new Exception("Wrong Birth Day.");
				if (!isInteger(monthTextBox.getText()) || Integer.valueOf(monthTextBox.getText()) < 1 || Integer.valueOf(monthTextBox.getText()) > 12) throw new Exception("Wrong Birth Month.");
				if (!isInteger(yearTextBox.getText()) || Integer.valueOf(yearTextBox.getText()) < 1900) throw new Exception("Wrong Birth Year.");
				java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
				Date parsedDate = dateFormat.parse(yearTextBox.getText() + "-" + monthTextBox.getText() + "-" + dayTextBox.getText());
				java.sql.Timestamp timestamp = new java.sql.Timestamp(parsedDate.getTime());
				tempUser.userBirthdate = timestamp.getTime()/1000;
				tempUser.userTimestamp = System.currentTimeMillis();
				
			}
			catch (Exception e)
			{
				showDialog(e.getMessage());
				return;
			}
		}
		else
		{
			showDialog("Error: Invalid data.");
			return;
		}
		
        try
        {
			Main.addToFile(new File(tableFileName), tempUser.toString());
			showDialog("Successfully added user!");
		}
		catch (Exception e)
		{
			showDialog("Error: " + e.getMessage());
			return;
		}
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobApplicationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobApplicationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobApplicationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobApplicationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobApplicationUI().setVisible(true);
            }
        });
    }
    
    public void showDialog(Object dialogText)
    {
		javax.swing.JOptionPane.showMessageDialog(this, String.valueOf(dialogText));
	}
	
	public void setCheckboxes()
	{
		jRadioButton1.setSelected(true);
        try
        {
			List<String> skillNames = Main.readFile(new File("skills.txt"));
			
			jCheckBox1.setText(skillNames.get(0));
			jCheckBox2.setText(skillNames.get(1));
			jCheckBox3.setText(skillNames.get(2));
			jCheckBox4.setText(skillNames.get(3));
			jCheckBox5.setText(skillNames.get(4));
			jCheckBox6.setText(skillNames.get(5));
			jCheckBox7.setText(skillNames.get(6));
			jCheckBox8.setText(skillNames.get(7));
			jCheckBox9.setText(skillNames.get(8));
			jCheckBox10.setText(skillNames.get(9));
			jCheckBox11.setText(skillNames.get(10));
			jCheckBox12.setText(skillNames.get(11));
			jCheckBox13.setText(skillNames.get(12));
			jCheckBox14.setText(skillNames.get(13));
			jCheckBox15.setText(skillNames.get(14));
			jCheckBox16.setText(skillNames.get(15));
			jCheckBox17.setText(skillNames.get(16));
			jCheckBox18.setText(skillNames.get(17));
			jCheckBox19.setText(skillNames.get(18));
			jCheckBox20.setText(skillNames.get(19));
			jCheckBox21.setText(skillNames.get(20));
			jCheckBox22.setText(skillNames.get(21));
			jCheckBox23.setText(skillNames.get(22));
			jCheckBox24.setText(skillNames.get(23));
			jCheckBox25.setText(skillNames.get(24));
			jCheckBox26.setText(skillNames.get(25));
			jCheckBox27.setText(skillNames.get(26));
			jCheckBox28.setText(skillNames.get(27));
			jCheckBox29.setText(skillNames.get(28));
			jCheckBox30.setText(skillNames.get(29));
			jCheckBox31.setText(skillNames.get(30));
			jCheckBox32.setText(skillNames.get(31));
			jCheckBox33.setText(skillNames.get(32));
			jCheckBox34.setText(skillNames.get(33));
			jCheckBox35.setText(skillNames.get(34));
			jCheckBox36.setText(skillNames.get(35));
			jCheckBox37.setText(skillNames.get(36));
			jCheckBox38.setText(skillNames.get(37));
			jCheckBox39.setText(skillNames.get(38));
			jCheckBox40.setText(skillNames.get(39));
			jCheckBox41.setText(skillNames.get(40));
			jCheckBox42.setText(skillNames.get(41));
			jCheckBox43.setText(skillNames.get(42));
			jCheckBox44.setText(skillNames.get(43));
			jCheckBox45.setText(skillNames.get(44));
			jCheckBox46.setText(skillNames.get(45));
			jCheckBox47.setText(skillNames.get(46));
			jCheckBox48.setText(skillNames.get(47));
			jCheckBox49.setText(skillNames.get(48));
			jCheckBox50.setText(skillNames.get(49));

		} catch (Exception e)
		{
			showDialog("Error: " + e.getMessage());
			this.dispatchEvent(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
		}		
	}
	public static boolean isInteger(String s, int radix) { // Code from https://stackoverflow.com/questions/5439529/determine-if-a-string-is-an-integer-in-java
		Scanner sc = new Scanner(s.trim());
		if(!sc.hasNextInt(radix)) return false;
		// we know it starts with a valid int, now make sure
		// there's nothing left!
		sc.nextInt(radix);
		return !sc.hasNext();
	}
	public static boolean isInteger(String s) {
		return isInteger(s,10);
	}	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup educationLevelGroup;
    private javax.swing.JTextField fullNameTextBox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField phoneNumberTextBox;
    private javax.swing.JTextField dayTextBox;
    private javax.swing.JTextField monthTextBox;
    private javax.swing.JTextField yearTextBox;
    private javax.swing.JButton resetButton;
    private javax.swing.ButtonGroup skillButtonGroup;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
